services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: library_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - api_db_data:/var/lib/postgresql/data

volumes:
  api_db_data: